import { parse } from "node-html-parser";

const ATTRIBUTION_TEXT = /powered by\s+(wisp|synscribe)/i;
const ATTRIBUTION_HREF = /(wisp\.blog|synscribe)/i;
const CHATGPT_SOURCE_TEXT =
  /^(source|via|generated by)\s*:?\s*chatgpt(\.com)?$/i;

const stripChatgptQuery = (href: string): string => {
  try {
    const url = new URL(href);
    let changed = false;
    for (const key of [...url.searchParams.keys()]) {
      const value = url.searchParams.get(key) || "";
      if (/chatgpt/i.test(key) || /chatgpt/i.test(value)) {
        url.searchParams.delete(key);
        changed = true;
      }
    }
    if (!changed) {
      return href;
    }
    const query = url.searchParams.toString();
    return `${url.origin}${url.pathname}${query ? `?${query}` : ""}${url.hash}`;
  } catch {
    return href.replace(/[?&][^=]+=[^&]*chatgpt[^&]*/gi, "").replace(/\?$/, "");
  }
};

export const stripChatgptSource = (html: string): string => {
  const root = parse(html);

  root.querySelectorAll("a").forEach((anchor) => {
    const href = anchor.getAttribute("href") || "";
    if (href) {
      anchor.setAttribute("href", stripChatgptQuery(href));
    }

    const text = (anchor.text || "").replace(/\s+/g, " ").trim();
    if (CHATGPT_SOURCE_TEXT.test(text)) {
      const parent = anchor.parentNode;
      anchor.remove();
      if (
        parent &&
        ["P", "SMALL", "EM", "SPAN"].includes((parent.tagName || "").toUpperCase()) &&
        !(parent.text || "").replace(/\s+/g, " ").trim()
      ) {
        parent.remove();
      }
    }
  });

  root.querySelectorAll("p, small, em, span").forEach((node) => {
    const text = (node.text || "").replace(/\s+/g, " ").trim();
    if (CHATGPT_SOURCE_TEXT.test(text)) {
      node.remove();
    }
  });

  return root.toString();
};

export const stripCmsAttribution = (html: string): string => {
  const root = parse(html);

  root.querySelectorAll("a").forEach((anchor) => {
    const text = (anchor.text || "").replace(/\s+/g, " ").trim();
    const href = anchor.getAttribute("href") || "";
    const isAttribution =
      ATTRIBUTION_TEXT.test(text) ||
      (ATTRIBUTION_HREF.test(href) && ATTRIBUTION_TEXT.test(text));

    if (!isAttribution) {
      return;
    }

    const parent = anchor.parentNode;
    anchor.remove();

    if (
      parent &&
      parent.tagName === "P" &&
      !(parent.text || "").replace(/\s+/g, " ").trim()
    ) {
      parent.remove();
    }
  });

  return stripChatgptSource(root.toString());
};

const normalizeUrl = (value: string) =>
  value.split("?")[0].replace(/&amp;/g, "&").trim();

export const stripLeadingFeaturedImage = (
  html: string,
  imageUrl: string | null
): string => {
  if (!imageUrl) {
    return html;
  }

  const featured = normalizeUrl(imageUrl);
  const featuredId = featured.split("/").filter(Boolean).at(-2) || "";
  const root = parse(html);

  root.querySelectorAll("img").forEach((img) => {
    const src = normalizeUrl(img.getAttribute("src") || "");
    const isFeatured =
      src === featured ||
      (featuredId.length > 8 && src.includes(featuredId));

    if (!isFeatured) {
      return;
    }

    const parent = img.parentNode;
    img.remove();

    if (!parent) {
      return;
    }

    const tag = (parent.tagName || "").toUpperCase();
    const leftover = (parent.text || "").replace(/\s+/g, " ").trim();
    if (
      ["P", "FIGURE", "DIV", "SPAN"].includes(tag) &&
      !parent.querySelector("img") &&
      !leftover
    ) {
      parent.remove();
    }
  });

  root.querySelectorAll("p").forEach((paragraph) => {
    if (!(paragraph.text || "").replace(/\s+/g, " ").trim() && !paragraph.querySelector("img")) {
      paragraph.remove();
    }
  });

  return root.toString();
};
